bike-web/Models/private_route.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------


namespace bike_web.Models
{

using System;
    using System.Collections.Generic;
    
    public partial class private_route
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public private_route()
        {
            this.private_route_comment = new HashSet<private_route_comment>();
        }
    
        public int id { get; set; }
        public int user_id { get; set; }
        public string article_title { get; set; }
        public Nullable<int> article_img_id { get; set; }
        public string article_img_info { get; set; }
        public string article_context { get; set; }
        public Nullable<System.DateTime> datetime { get; set; }
        public Nullable<int> fav_num { get; set; }
        public Nullable<int> seem_num { get; set; }
        public Nullable<int> star_num_sum { get; set; }
        public Nullable<int> sum_people_give_star { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<private_route_comment> private_route_comment { get; set; }
    }
}

bike-web/ViewModels/PrivateRouteViewModel.cs
using bike_web.Models;
using System;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace bike_web.ViewModels
{
    public class PrivateRouteData
    {
        public int p_ID { get; set; }
        public string p_artitle_title { get; set; }
        [DisplayName("文章名稱")]
        public string p_artitle_img_info { get; set; }
        [DisplayName("文章照片")]
        public DateTime p_datetime { get; set; }
        [DisplayName("po文日期")]
        public double? p_seen_num { get; set; }
        [DisplayName("觀看次數")]
        public double? p_star_num_sum { get; set; }
        [DisplayName("星星總數")]

        public double? p_sum_people_give_star_num { get; set; }
        [DisplayName("星星總評分人數")]
        public string p_content { get; set; }
        [DisplayName("文章內容")]
        //public double? p_star { get; set; }
        //[DisplayName("星星評分")]
        public string u_username { get; set; }
        [DisplayName("文章投稿人")]
        public int u_userID { get; set; }
        public int p_fav { get; set; }

        public List<string> hashtag { get; set; } 

    }
   

   

    public class PrivateRouteViewModel
    {

        public List<PrivateRouteData> 熱門文章資訊 { get; set; }
        
       

    }

   


}

bike-web/Controllers/PrivateRouteController.cs
using bike_web.Models;
using bike_web.ViewModels;
using PagedList;
using System;
using System.Collections.Generic;
using System.Data.SqlTypes;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace bike_web.Controllers
{
    public class PrivateRouteController : Controller
    {
        // GET: PrivateRoute
        // GET: PrivateRoute
        //public ActionResult PrivateRoute()
        //{
        //    return View();
        //}

        public ActionResult privateRoutePage(int? articletitleid)
        {
            var Sid = Convert.ToInt32(Session["ID"]);
            List<string> hashtags = new List<string>();

            if (articletitleid != null)
            {
                var db = new KSBikeEntities();
                var y = db.private_route.Where(k => k.id == articletitleid).FirstOrDefault();
                if (y == null)
                {
                    return RedirectToAction("privateRoutePage", new { articletitleid = 1 });
                }
                Session["articletitleid"] = articletitleid;
                y.seem_num += 1;
                db.SaveChanges();


                //db.Database.CommandTimeout = 3 * 60;
                List<private_route_comment> PrivateRouteComments = db.private_route_comment.Where(k => k.article_title_id == articletitleid).ToList();
                //
                List<commentWithName> 留言資訊 = new List<commentWithName>();
                foreach (var item in PrivateRouteComments)
                {
                    commentWithName z = new commentWithName();
                    z.id = item.id;
                    z.comment_user_name = db.users.Where(x => x.id == item.comment_user_id).FirstOrDefault().username;
                    z.user_give_star_num = item.user_give_star_num;
                    z.comment = item.comment;
                    z.datetime = (DateTime)item.datetime;
                    留言資訊.Add(z);



                }










                thePrivateRouteData 熱門文章 = (from p in db.private_route
                                            join u in db.users on p.user_id equals u.id
                                            where p.id == (int)articletitleid
                                            select new thePrivateRouteData
                                            {
                                                u_userID = u.id,
                                                u_username = u.username,
                                                p_ID = p.id,
                                                p_artitle_title = p.article_title,
                                                p_artitle_img_info = p.article_img_info,
                                                p_datetime = (DateTime)p.datetime,
                                                p_seen_num = p.seem_num,
                                                p_star_num_sum = p.star_num_sum,
                                                p_sum_people_give_star_num = p.sum_people_give_star,
                                                p_content = p.article_context,
                                                //p_star = star_point( p.star_num_sum, p.sum_people_give_star)

                                            }).FirstOrDefault();
                //判斷有沒有在我的最愛


                int[] fav = db.user_favorite.Where(d => d.user_fav_id == Sid).Select(a => a.private_route_id).ToArray();

                if (fav.Contains(熱門文章.p_ID))
                {
                    熱門文章.p_fav = 1;
                }
                else
                {
                    熱門文章.p_fav = 0;
                }


                //捕捉每篇文章hashtag
                var hahtags = db.hashtags.Where(d => d.private_route_id == 熱門文章.p_ID).ToArray();

                if (hahtags == null)
                {
                    PrivateRouteandCommentViewModel vm = new PrivateRouteandCommentViewModel()
                    {
                        熱門文章 = 熱門文章,
                        留言資訊 = 留言資訊,

                    };


                    //
                    return View(vm);

                }
                else
                {
                    foreach (var item in hahtags)
                    {
                        hashtags.Add(item.hashtag_name);

                    }
                    PrivateRouteandCommentViewModel vm1 = new PrivateRouteandCommentViewModel()
                    {
                        熱門文章 = 熱門文章,
                        留言資訊 = 留言資訊,
                        HashTags = hashtags
                    };



                    return View(vm1);


                }





            }
            return View();


        }

        //public ActionResult AddMessage()
        //{

        //    int AddMessageNum = (int)TempData["TDMessage"];
        //    AddMessageNum += 1;
        //    TempData["TDMessage"] = AddMessageNum.ToString();

        //    return RedirectToAction("PrivateRoute", new { articletitleid = 1 });


        //}


        [HttpPost]
        public ActionResult saveMessage()
        {
            int starnum = 0;
            string starnumtext = Request.Form["txtNum"].Trim();
            int articleid = Convert.ToInt32(Session["articletitleid"]);
            if (starnumtext == "1")
            {
                starnum = 1;
            }
            else if (starnumtext == "2")
            {
                starnum = 2;
            }
            else if (starnumtext == "3")
            {
                starnum = 3;
            }
            else if (starnumtext == "4")
            {
                starnum = 4;
            }
            else if (starnumtext == "5")
            {
                starnum = 5;
            }
            else
            {
                starnum = 0;
            }

            SqlDateTime myDateTime = DateTime.Now;
            //DateTime nowdateTime = DateTime.Now;
            //string sqlFormattedDate = nowdateTime.ToString("yyyy-MM-dd HH:mm:ss.fff");
            KSBikeEntities db = new KSBikeEntities();
            private_route_comment x = new private_route_comment();


            x.article_title_id = articleid;
            x.comment_user_id = Convert.ToInt32(Session["ID"]);


            x.user_give_star_num = starnum;
            x.comment = Request.Form["txtComment"];
            x.datetime = (DateTime)myDateTime;
            db.private_route_comment.Add(x);
            db.SaveChanges();

            var y = db.private_route.Where(k => k.id == articleid).FirstOrDefault();
            y.star_num_sum += starnum;
            y.sum_people_give_star += 1;
            db.SaveChanges();

            return RedirectToAction("privateRoutePage", new { articletitleid = articleid });
        }

        [HttpPost]
        public ActionResult addToMyFav(int articleid)
        {
            string message = "";
            int Sid = Convert.ToInt32(Session["id"]);
            KSBikeEntities db = new KSBikeEntities();

            var myfav = db.user_favorite.Where(m => m.user_fav_id == Sid && m.private_route_id == articleid).FirstOrDefault();


            if (myfav == null)
            {
                user_favorite x = new user_favorite();
                SqlDateTime myDateTime = DateTime.Now;
                x.datetime = (DateTime)myDateTime;
                x.user_fav_id = Sid;
                x.private_route_id = articleid;
                x.official_route_id = 0;
                db.user_favorite.Add(x);
                db.SaveChanges();
                message = "add";
            }
            else
            {
                db.user_favorite.Remove(myfav);
                db.SaveChanges();
                message = "delete";
            }

            return Json(message, JsonRequestBehavior.AllowGet);



        }



        int pageSize = 9;

        //這裡開始
        public ActionResult privateRoute(string hashtag, int page =1)
        {



            if (Session["id"] == null)
            {
                return RedirectToAction("Index", "Home");

            }
            else
            {


                int currentPage = page < 1 ? 1 : page;


                var Sid = Convert.ToInt32(Session["ID"]);



                KSBikeEntities db = new KSBikeEntities();

                //先拿到PR的id
                var privateRouteIds = db.hashtags.Where(x => x.hashtag_name == hashtag).OrderByDescending(e => e.id).ToList(); ;


                List<PrivateRouteData> 熱門文章資訊 = new List<PrivateRouteData>();

                foreach (var item in privateRouteIds)
                {

                    private_route y = db.private_route.Where(z => z.id == item.private_route_id).FirstOrDefault();
                    PrivateRouteData x = new PrivateRouteData();
                    x.u_userID = y.user_id;
                    x.u_username = db.users.Where(a => a.id == y.user_id).FirstOrDefault().username;
                    x.p_ID = y.id;
                    x.p_artitle_title = y.article_title;
                    x.p_artitle_img_info = y.article_img_info;
                    x.p_datetime = (DateTime)y.datetime;
                    x.p_seen_num = y.seem_num;
                    x.p_star_num_sum = y.star_num_sum;
                    x.p_sum_people_give_star_num = y.sum_people_give_star;
                    x.p_content = y.article_context;
                    熱門文章資訊.Add(x);

                }










                var result = 熱門文章資訊.ToPagedList(currentPage, pageSize);


                //PrivateRouteViewModel prv = new PrivateRouteViewModel
                //{
                //    熱門文章資訊 = 熱門文章資訊
                //};


                int[] fav = db.user_favorite.Where(d => d.user_fav_id == Sid).Select(a => a.private_route_id).ToArray();
                foreach (PrivateRouteData item in result)
                {
                    item.hashtag = db.hashtags.Where(e => e.private_route_id == item.p_ID).Select(f => f.hashtag_name).ToList();

bike-web/Views/PrivateRoute/privateRoute.cshtml
@using PagedList
@using PagedList.Mvc
@model IPagedList<bike_web.ViewModels.PrivateRouteData>


<link href="~/Content/PagedList.css" rel="stylesheet" />



@{
    ViewBag.Title = "privateRoute";
}

<section class="page-section" id="contact">
    <div class="container">

        <div class="row">
            @foreach (var item in Model)
            {
                @Html.Partial("_PrivateRouteCard", item)

            }

        </div>



        <div class="row">
            <div class="col">
                <nav aria-label="Page navigation example">
                    <ul class="pagination justify-content-center">
                        @Html.PagedListPager((IPagedList)Model, x => Url.Action("privateRoute", new { hashtag = Session["hashtag"].ToString(), page = x }))
                    </ul>
                </nav>
            </div>
        </div>
    </div>
</section>

bike-web/Views/PrivateRoute/privateRoutePage.cshtml
@using bike_web.ViewModels


@{
    ViewBag.Title = "privateRoutePage";
}
@section Scripts {

    <script src="@Url.Content("~/Scripts/vendor/js/jquery-3.4.1.js")" type="text/javascript"></script>
    <script src="~/Scripts/js/privateRoutePage.js"></script>
    <style type="text/css">

        .s {
            font-size: 40px;
        }

        .infoStar {
            font-size: 40px;
            color: #F4D19B;
        }

        #messagebody {
            display: none;
        }

        .infomessage {
            border-width: 3px;
            border-style: solid;
            border-color: #D7E9F7;
            padding: 1px;
        }
    </style>


}





@model bike_web.ViewModels.PrivateRouteandCommentViewModel
<body class="container">
    <div class="row  justify-content-center">
        <img src="@Url.Content(Model.熱門文章.p_artitle_img_info)" alt="" class="">
        <div class="text-center">
            <p class="fw-bold text-center font-32 my-3 pb-3">@Model.熱門文章.p_artitle_title</p>
            <div class="d-flex justify-content-between ">
                <h3><span class="badge bg-light text-darkBrown ml-3  mt-5 ">紀錄者:@Model.熱門文章.u_username</span></h3>
                <div>
                    @if (Model.熱門文章.p_fav == 0)
                    {
                        <button type="button" value="@Model.熱門文章.p_ID" class="btnFav btn rounded-pill btn-outline-danger h-50 ">
                            <i class="iFav bi fs-5 bi-heart" value="@Model.熱門文章.p_ID"></i>
                        </button>
                    }
                    else
                    {
                        <button type="button" value="@Model.熱門文章.p_ID" class="btnFav rounded-pill btn btn-danger h-50 ">
                            <i class="iFav bi fs-5 bi-heart" value="@Model.熱門文章.p_ID"></i>
                        </button>
                    }
                </div>
            </div>
            <div class="d-flex justify-content-between py-2">
                <div class=" px-3 font-20"><span>@Model.熱門文章.p_datetime</span></div>
            </div>
            <div class="d-flex justify-content-end py-2 ">
                @{if (Model.HashTags != null)
                    {
                        foreach (string hashtag in Model.HashTags)
                        {
                            <a href="@Url.Action("privateRoute", "PrivateRoute", new { hashtag = hashtag })" class="link-info"><p> #@hashtag </p></a><p>&nbsp</p>
                        }
                    }
                }
            </div>
        </div>
        <hr class="divider" />
        <div class="text-left">
            @Html.Raw(@Model.熱門文章.p_content)
        </div>
        <div class="d-flex justify-content-between">
            <div><i class="bi bi-eye fs-4"></i><span class="ms-2">@Model.熱門文章.p_seen_num</span></div>
            @*重新計算星星*@
            @{double star;
            }
            @if (Model.熱門文章.p_sum_people_give_star_num is null)
            {
                star = 0;

            }
            else if (Model.熱門文章.p_sum_people_give_star_num == 0)
            {
                star = 0;
            }
            else
            {
                star = (double)Math.Round((decimal)(int)Model.熱門文章.p_star_num_sum / (int)Model.熱門文章.p_sum_people_give_star_num, 2);
            }
            <div id="starNumber" class="text-primary"><i class="bi bi-star-fill fs-4"></i><span class="ms-2">@star</span></div>
        </div>
    </div>
    @*@model List<private_route_comment>*@

    @*透過ajax傳送*@
    <div class="card">
        <!--Submit form-->
        @*@using (Html.BeginForm("Submit", "Comment"))
            {*@
        <form id="commentForm" method="post" action="~/PrivateRoute/saveMessage">



            <h5 class="text-center bg-light rounded-1 border-start border-end border-4 border-primary py-2 fw-bold tracking-3">我的評價</h5>
            <div class="card-body ">
                <div class="row  justify-content-start">
                    <div class="col-2 text-center score_star">
                        <span id="star1" class="s">★</span>
                        <span id="star2" class="s">★</span>
                        <span id="star3" class="s">★</span>
                        <span id="star4" class="s">★</span>
                        <span id="star5" class="s">★</span>
                        <p id="starCount"></p>
                        <input name="txtNum" id="starNum" style="display:none;" />
                    </div>
                </div>
                <div class="row  justify-content-center">
                    <div class="text-center my-2 ">
                        @*原本id有exampleFormControlTextarea1*@
                        <textarea name="txtComment" wrap="hard" style="word-wrap : break-word;" class="form-control comment" id="txtComment" placeholder="內容" rows="3"></textarea>
                    </div>
                </div>
                @*<input type="button" class="btn btn-primary send" value="送出" disabled>*@
                <button id="btnSave" type="button" class="btn btn-primary send" value="@Model.熱門文章.p_ID" @*ValidateRequest=”false”*@ disabled>送出</button>
            </div>
        </form>

        <!--捕捉星星-->
        <script>
            let spans = document.querySelectorAll("body div form div div div span.s");
            for (let span of spans) {
                span.addEventListener("mouseover", mouseOver);
                span.addEventListener("mouseout", mouseOut);
                span.addEventListener("click", Click);
                span.addEventListener("dblclick", dblClick);
            }
            let starCount = document.getElementById('starCount');
            let starNum = document.getElementById('starNum');

            var startruehere;
            starCount.innerHTML = '目前尚未評分';
            starNum.innerHTML = 0;

            function mouseOver() {
                let starhere = this.id.charAt(4);
                for (let j = 0; j < 5; j++) {
                    spans[j].style.color = "#000";
                }
                for (let i = 0; i < starhere; i++) {
                    spans[i].style.color = "#F4D19B";
                }
                starCount.innerHTML = '確定評分為' + starhere + '星級嗎?';
            }
            function mouseOut() {
                for (let j = 0; j < 5; j++) {
                    spans[j].style.color = "#000";
                }
                for (let i = 0; i < startruehere; i++) {
                    spans[i].style.color = "#F4D19B";
                }
                if (startruehere > 0 && startruehere < 6) {
                    starCount.innerHTML = startruehere + "星級";
                    starNum.value = startruehere;
                }
                else {
                    starCount.innerHTML = '目前尚未評分';
                    starNum.value = 0;
                }

            }



            function Click() {
                startruehere = this.id.charAt(4);


                for (let j = 0; j < 5; j++) {
                    spans[j].style.color = "#000";
                }
                for (let i = 0; i < startruehere; i++) {
                    spans[i].style.color = "#F4D19B";
                }

                starCount.innerHTML = startruehere + "星級";
                starNum.value = startruehere;

            }

            function dblClick() {
                for (let j = 0; j < 5; j++) {
                    spans[j].style.color = "#F4D19B";
                }
                startruehere = 0;
                starCount.innerHTML = '目前尚未評分';
                starNum.value = 0;
            }








        </script>

        <form>
            <h5 class="text-center bg-light rounded-1 border-start border-end border-4 border-primary py-2 fw-bold tracking-3">路線相關評價</h5>
            <div class="card-body ">
                <div class="row  justify-content-center">
                    <div class="text-center my-2 ">


                        @*從這裡開始匯入評論*@
                        <div class="messageList" id="messagebody1" rows="3">
                            @{
                                int count = 0;
                                Model.留言資訊.Reverse();
                                foreach (var t in Model.留言資訊)
                                {
                                    count++;
                                    <div class="infomessage">
                                        <p class="infoName">@t.comment_user_name</p>
                                        @if (@t.user_give_star_num.ToString() == "1")
                                        {
                                            <p class="infoStar">★</p>
                                        }
                                        else if (@t.user_give_star_num.ToString() == "2")
                                        {
                                            <p class="infoStar">★★</p>
                                        }
                                        else if (@t.user_give_star_num.ToString() == "3")
                                        {
                                            <p class="infoStar">★★★</p>
                                        }
                                        else if (@t.user_give_star_num.ToString() == "4")
                                        {
                                            <p class="infoStar">★★★★</p>
                                        }
                                        else if (@t.user_give_star_num.ToString() == "5")
                                        {
                                            <p class="infoStar">★★★★★</p>
                                        }
                                        else
                                        {
                                            <p class="infoStar"></p>
                                        }
                                        <p class="infoText">@t.comment</p>
                                        <p class="infoTime">@t.datetime</p>
                                    </div>
                                    if (count == 5)
                                    {
                                        break;
                                    }
                                }
                            }

                        </div>
                        <nav aria-label="Page navigation example" id="commentPage">
                            <ul class="pagination justify-content-center">
                                @{ int pageNumber = 0;


                                    if (Model.留言資訊.Count % 5 > 0)
                                    {
                                        pageNumber = (Model.留言資訊.Count / 5) + 1;

                                    }
                                    else
                                    {
                                        pageNumber = Model.留言資訊.Count / 5;
                                    }

                                    if (pageNumber == 0)
                                    {
                                        return;
                                    }
                                    else
                                    {
                                        for (int i = 1; i <= pageNumber; i++)
                                        {
                                            if (i == 1)
                                            {
                                                <li class="page-item  disabled"><a class="page-link active" href="javascript:;">@i</a></li>
                                            }
                                            else
                                            {
                                                <li class="page-item"><a class="page-link" href="javascript:;">@i</a></li>
                                            }
                                        }
                                    }



                                }


                            </ul>
                        </nav>


                    </div>













                </div>
            </div>
        </form>
    </div>





</body>