bike-web/Controllers/OnlyOffRouteController.cs
using bike_web.Models;
using bike_web.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Data.SqlTypes;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace bike_web.Controllers
{
    public class OnlyOffRouteController : Controller
    {
        // GET: OnlyOffRoute
        public ActionResult List(int id)
        {
            ViewBag.homeID = id;
            var avgStar = (new OnlyOffR_F()).refreshAvgStar(id);
            ViewBag.avgStar = avgStar;
            int userID = Convert.ToInt32(Session["id"]);

            KSBikeEntities db = new KSBikeEntities();
            offRouteViewModel vm = new offRouteViewModel();
            official_route_data offRoutes = db.official_route_data.FirstOrDefault(r => r.home_id == id);
            if (offRoutes != null)
            {
                var 單一官方路線 = (from h in db.Homes
                              join od in db.official_route_data on h.id equals od.home_id
                              where od.home_id == id
                              select new offRoute
                              {
                                  h_ID = h.id,
                                  h_description = h.hdescription,
                                  h_name = h.hname,
                                  h_distance = (double?)h.hdistance,
                                  h_rank = h.hrank,
                                  h_img = h.himg,
                                  od_homeID = od.home_id,
                                  od_offRouteID = od.id,
                                  od_official_data_catalog = od.official_data_catalog,
                                  od_official_data_img = od.official_data_img,
                                  od_official_data_img_content = od.official_data_content,
                                  od_official_data_img_info = od.official_data_img_info,
                              }).ToList();

                var 路線評論 = (new OnlyOffR_F()).QrouteComment((int)id);

                var 路線標籤 = (from tag in db.hashtags
                            where tag.official_route_id == id
                            select new routeHashtag
                            {
                                id = tag.id,
                                hashtag_name = tag.hashtag_name,
                                private_route_id = tag.private_route_id
                            }).ToList();
                var 我的最愛 = (from h in db.Homes
                            join fav in db.user_favorite on h.id equals fav.official_route_id
                            where fav.user_fav_id == userID && fav.official_route_id > 1
                            select new userFav
                            {
                                id = fav.id,
                                official_route_id = fav.official_route_id
                            }).OrderBy(e => e.id).ToList();
                vm.offcialAllRoute = 單一官方路線;
                vm.RouteComment = 路線評論;
                if (路線標籤 != null) { vm.RouteHashtag = 路線標籤; }
                vm.checkFav = 我的最愛;

            }
            return View(vm);
        }



        [HttpPost]
        public ActionResult SaveReview()    //saveReview
        {
            SqlDateTime myDateTime = DateTime.Now;
            var homeID = int.Parse(Request.Form["homeID"]);
            var userID = int.Parse(Request.Form["txtUserID"]);
            int starnum = 0;

            string starnumtext = Request.Form["txtNum"].Trim();
            if (Regex.IsMatch(starnumtext, @"^[0-9]+$"))
            {
                starnum = int.Parse(starnumtext);
            }
            else starnum = 0;

            KSBikeEntities db = new KSBikeEntities();
            official_route_comment x = new official_route_comment();

            x.article_title_id = homeID;
            x.comment_user_id = (int)userID;
            x.user_give_star_num = starnum;
            x.comment = Request.Form["userComment"];
            x.datetime = (DateTime)myDateTime;
            db.official_route_comment.Add(x);
            db.SaveChanges();
            var avgStar = (new OnlyOffR_F()).refreshAvgStar(homeID);
            (new OnlyOffR_F()).updateAvgStar(homeID, avgStar);
            ViewBag.avgStar = avgStar;
            return RedirectToAction("List", new { id = homeID });
        }



        [HttpPost]
        public ActionResult UpdateFavorite(int articleid)
        {

            string message = "";
            int userID = Convert.ToInt32(Session["id"]);
            KSBikeEntities db = new KSBikeEntities();

            var myfav = db.user_favorite.Where(m => m.user_fav_id == userID && m.official_route_id == articleid).FirstOrDefault();


            if (myfav == null)
            {
                user_favorite x = new user_favorite();
                SqlDateTime myDateTime = DateTime.Now;
                x.datetime = (DateTime)myDateTime;
                x.user_fav_id = userID;
                x.private_route_id = 0;
                x.official_route_id = articleid;
                db.user_favorite.Add(x);
                db.SaveChanges();
                message = "add";
            }
            else
            {
                user_favorite x = new user_favorite();
                SqlDateTime myDateTime = DateTime.Now;
                x.datetime = (DateTime)myDateTime;
                x.official_route_id = 1;
                //db.user_favorite.Remove(myfav);
                db.SaveChanges();
                message = "delete";
            }

            return Json(message, JsonRequestBehavior.AllowGet);
        }



        //[HttpPost]
        public ActionResult findHashtag(int homeID, string hashtag)
        {
            KSBikeEntities db = new KSBikeEntities();
            offRouteViewModel vm = new offRouteViewModel();
            var avgStar = (new OnlyOffR_F()).refreshAvgStar(homeID);
            ViewBag.avgStar = avgStar;

          
            var 路線標籤 = (from h in db.Homes
                        join tag in db.hashtags on h.id equals tag.official_route_id                       
                        where tag.hashtag_name == hashtag
                        select new offRoute
                        {
                            h_ID = h.id,
                            h_description = h.hdescription,
                            h_name = h.hname,
                            h_distance = (double?)h.hdistance,
                            h_rank = h.hrank,
                            h_img = h.himg,

                            //mia
                            hashtag_name = tag.hashtag_name,
                            private_route_id = tag.private_route_id
                        }).ToList();
            vm.offcialAllRoute = 路線標籤;
            return View(vm);
        }
    }
}

bike-web/Views/OnlyOffRoute/findHashtag.cshtml
@model bike_web.ViewModels.offRouteViewModel
@{
    ViewBag.Title = "findHashtag";
}

<div class="container animation my-3 ">
    <div id="app">
        <!-- all route -->
        <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="nav-all" role="tabpanel" aria-labelledby="nav-all-tab">
                <div class="row">
                    @foreach (var item in Model.offcialAllRoute)
                    {

                        int count = 0; bool btn = true;
                        <div class="col-lg-4 col-md-6">
                            <div class="portfolio-item card mb-3">
                                <span>
                                    <a href="@Url.Action("List","OnlyOffRoute",new {id=item.h_ID})"><img src="~/images/home/@item.h_img" class="card-img-top portfolio-img" alt="@item.h_name" /></a>
                                    <div class="portfolio-info">
                                        <h3>@item.h_name</h3>
                                    </div>
                                </span>
                                <div class="card-body">
                                    <div class="position-absolute" style="top: 20px; right: 20px">
                                        @*//mia:我的最愛*@
                                        @if (Session["id"] != null)
                                        {
                                            <form method="post">
                                                @foreach (var fav in @Model.offcialAllRoute)
                                                {
                                                    count++;
                                                    if (fav.official_route_id == item.h_ID)
                                                    {
                                                        btn = false;
                                                        <button type="button" value="@item.h_ID" class="btnFav rounded-pill btn btn-danger ">
                                                            <i class="iFav bi fs-5 bi-heart" @*value="@Model.p_ID"*@></i>
                                                        </button>
                                                        //count++;
                                                    }
                                                    else if (btn)
                                                    {
                                                        if (count < @Model.offcialAllRoute.Count()) { continue; }
                                                        <button type="button" class="btnFav btn rounded-pill btn-outline-danger " value="@item.h_ID">
                                                            <i class="iFav bi fs-5 bi-heart"></i>
                                                        </button>}
                                                }
                                            </form>
                                            @*//END---我的最愛*@
                                        }
                                        else
                                        {
                                            <button v-on:click="greet" type="button" class="btnLoginYet btn rounded-pill btn-outline-danger " value="">
                                                <i class="bi fs-5 bi-heart"></i>
                                            </button>}
                                    </div>
                                    <h5 class="border-bottom border-3 border-primary"></h5>
                                    <div class="d-flex justify-content-between pb-2 mb-2 flex-lg-row flex-md-column">
                                        <div class="badge bg-light font-20 text-darkBrown px-3">長度:@item.h_distance km</div>
                                        <div class="badge bg-darkBrown font-20 px-3">難度:<span class="text-primary font-20">@item.h_rank</span></div>
                                    </div>
                                    <p class="card-text">@item.h_description</p>
                                    <div class="d-flex justify-content-end">
                                        <div class="text-primary"><span class="font-24 s mx-1" style="color: #F4D19B">★</span>@ViewBag.avgStar</div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    }
                </div>
            </div>

        </div>
    </div>
</div>

<script src="~/Scripts/js/myFavorite.js"></script>